name: auto-pull-request
on: [pull_request]

jobs:

  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

  automerge:
    runs-on: ubuntu-latest
    needs: label
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@ecb16453ce68e85b1e23596c8caa7e7499698a84"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "shipit"
          MERGE_REMOVE_LABELS: "shipit"
          MERGE_METHOD: "squash"
          UPDATE_METHOD: "rebase" 
